spring:
  datasource:
    url: {Url}
    username: {Username}
    password: {Password}
    driver-class-name: org.postgresql.Driver
  application:
      name: brdo-company
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  web:
    resources:
      add-mappings: false
  server:
    error:
      whitelabel:
        enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
