spring:
  datasource:
    url: jdbc:postgresql://awsaurora16-instance-1.ctg8u4ia637r.eu-north-1.rds.amazonaws.com:5432/school_registry
    username: postgres
    password: Polimorftitanoop123+**
    driver-class-name: org.postgresql.Driver
  application:
      name: brdo-company
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
  web:
    resources:
      add-mappings: false
  server:
    error:
      whitelabel:
        enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8087

